

export const callAstroData = [
  {
    id: 1,
    src: "/ds-img/sachin.svg",
    alt: "Astro Image",
    ulname: "Astro Sachin ",
    expas: 5,
    reve: 4.85,
    ordr: 6600,
    skill: "Vedic, Tarot, Neumrology", 
    lang: "Hindi, English",
    prcl: 20,
    prclf: 30,
    celeb: "Celebrity",
  },
  {
    id: 2,
    src: "/ds-img/parth.svg",
    alt: "Chat",
    ulname: " Parth",
    expas: 10,
    reve: 4.5,
    ordr: 2000,
    skill: "Vedic,  Neumrology",
    lang: "Hindi, Malyalam, Sindi",
    prcl: 12,
    prclf: 30,
    celeb: "Best Vedic",
  },
  {
    id: 3,
    src: "/ds-img/anvi.svg",
    alt: "Match",
    ulname: "Tarot Anvi",
    expas: 2,
    reve: 3.85,
    ordr: 600,
    skill: "Vedic, Tarot ",
    lang: "Kannada",
    prcl: 2,
    prclf: 30,
    celeb: "Top Rating",
  },
  {
    id: 4,
    src: "/ds-img/anshika.svg",
    alt: "Live",
    ulname: "Astro Anvi",
    expas: 8,
    reve: 4.25,
    ordr: 5600,
    skill: "Vedic ",
    lang: "Hindi, Marathi",
    prcl: 10,
    prclf: 30,
    celeb: "Special",
  },
  {
    id: 5,
    src: "/ds-img/shefali.svg",
    alt: "Store",
    ulname: "Tarot Shefali ",
    expas: 7,
    reve: 4.95,
    ordr: 6100,
    skill: "Palmistry, Tarot, Neumrology",
    lang: "Punjabi, English",
    prcl: 15,
    prclf: 30,
    celeb: "Top Choice",
  },
];

export const chatAstroData = [
  {
    id: 1,
    src: "/ds-img/sachin.svg",
    alt: "Astro Image",
    ulname: "Astro Sachin ",
    expas: 5,
    reve: 4.85,
    ordr: 6600,
    skill: "Vedic, Tarot, Neumrology",
    lang: "Hindi, English",
    prct: 10,
    prctf: 15,
    celeb: "Celebrity",
  },
  {
    id: 2,
    src: "/ds-img/parth.svg",
    alt: "Chat",
    ulname: " Parth",
    expas: 10,
    reve: 4.5,
    ordr: 2000,
    skill: "Vedic,  Neumrology",
    lang: "Hindi, Malyalam, Sindi",
    prct: 18,
    prctf: 38,
    celeb: "Best Vedic",
  },
  {
    id: 3,
    src: "/ds-img/anvi.svg",
    alt: "Match",
    ulname: "Tarot Anvi",
    expas: 2,
    reve: 3.85,
    ordr: 600,
    skill: "Vedic, Tarot ",
    lang: "Kannada",
    prct: 24,
    prctf: 30,
    celeb: "Top Rating",
  },
  {
    id: 4,
    src: "/ds-img/anshika.svg",
    alt: "Live",
    ulname: "Astro Anvi",
    expas: 8,
    reve: 4.25,
    ordr: 5600,
    skill: "Vedic ",
    lang: "Hindi, Marathi",
    prct: 20,
    prctf: 12,
    celeb: "Special",
  },
  {
    id: 5,
    src: "/ds-img/shefali.svg",
    alt: "Store",
    ulname: "Tarot Shefali ",
    expas: 7,
    reve: 4.95,
    ordr: 6100,
    skill: "Palmistry, Tarot, Neumrology",
    lang: "Punjabi, English",
    prct: 55,
    prctf: 35,
    celeb: "Top Choice",
  },
];
//  const astroData = [...chatAstroData, ...callAstroData];



